#!/bin/bash

if [[ -z "$1" ]]; then
echo -e "\
\nusage:\tclCurlj clientCode URL \n
eg:\tclCurl l http://127.0.0.1:8000/ping\
\nvalid profile flags are: \n\
s - SFTP \n\
l - localSandbox \n\
e - etl \n\
t - etlTest \n\
r - mattRandom2 \n\
";
exit 1;
elif [[ -z "$2" ]]; then
echo "A URL is required";
exit 1;
fi

URL=$2;

case "$1" in

"s" )
	userName="SFTP";
	password="123";
	;;
"l" )
	userName="localSandbox";
	password="123";
	;;
"e" )
	userName="etl";
	password="123";
	;;
"t" )
	userName="etlTest";
	password="123";
	;;
"r" )
	userName="mattRandom2";
	password="123";
	;;
esac

	curl -i -H "username:$userName" -H "password:$password" $URL
	echo -e "\n\nFROM: curl -i -H "username:$userName" -H "password:$password" $URL"