#!/bin/bash


parameterFolderPath="$CLOVERLEAF_BASE_PATH/config/parameterFiles/testing/current/assembledParameterSets";

if [[ -z "$1" ]]; then
filePath="$parameterFolderPath/jmcPlansToFile.json"

else
filePath="$parameterFolderPath/$1.json"
fi


if [[ ! -f "$filePath" ]]; then

echo -e "$filePath does not exist";
exit 1;
fi

echo -e "executing:\n \
$cloverleaf --file=$filePath --overrideParentPath=$dataLinkDir/mainDataDestination/clJson/ \n"


$cloverleaf --file=$filePath --overrideParentPath=$dataLinkDir/mainDataDestination/clJson/
#$cloverleaf  --file=$filePath --saveDB
#$cloverleaf  --file=$filePath --verbose
#$cloverleaf  --file=$filePath