#!/bin/bash



if [[ "jl" == "$1" ]]; then
fileName="jmcLocalTestData"
echo "SET JMC from localSandbox";
cp $CLOVERLEAF_BASE_PATH/config/profile/otherCloverleafIdentities/$fileName.js $CLOVERLEAF_BASE_PATH/config/profile/cloverleaf.js

elif [[ "js" == "$1" ]]; then
fileName="jmcSftp"
echo "SET JMC from SFTP"
cp $CLOVERLEAF_BASE_PATH/config/profile/otherCloverleafIdentities/$fileName.js $CLOVERLEAF_BASE_PATH/config/profile/cloverleaf.js

elif [[ "etl" == "$1" ]]; then
fileName="lpSchemaEtlDb"
echo "SET LP Schema from ETL Database Server"
cp $CLOVERLEAF_BASE_PATH/config/profile/otherCloverleafIdentities/$fileName.js $CLOVERLEAF_BASE_PATH/config/profile/cloverleaf.js

elif [[ "l" == "$1" ]]; then
fileName="localSandbox"
echo "SET localSandbox"
cp $CLOVERLEAF_BASE_PATH/config/profile/otherCloverleafIdentities/$fileName.js $CLOVERLEAF_BASE_PATH/config/profile/cloverleaf.js

else
echo "NO CHANGE";
cat $CLOVERLEAF_BASE_PATH/config/profile/cloverleaf.js | grep "userName:";
echo -e " \n\
try: \n\
jl - jmcLocalTestData \n\
js - SET JMC from SFTP
etl - lpSchemaEtlDb \n\
l - localSandbox \n\
";
fi


