#!/bin/bash
$cloverleaf  --file=$clTestScriptsDir/parameterFiles/cloverMoodleSource/current/assembledParameterSets/cmPrimary/cmBarnesville010.js
$cloverleaf  --file=$clTestScriptsDir/parameterFiles/cloverMoodleSource/current/assembledParameterSets/cmPrimary/cmPact010.js
$cloverleaf  --file=$clTestScriptsDir/parameterFiles/cloverMoodleSource/current/assembledParameterSets/cmSecondary/cmPact013.js
